### ISSUE TITLE
Standard JSON path

### ISSUE THREAD

**Issue by leonchen83** [RedisLabsModules/rejson#18] opened 2017-05-04 02:57 UTC
this issue similar with [#1](https://github.com/RedisLabsModules/rejson/issues/1), but [RFC6901](https://tools.ietf.org/html/rfc6901) provide a simpler way to access json object.  
could this project support [that](https://tools.ietf.org/html/rfc6901) syntax?

**Comment by itamarhaber** [comment] 2017-05-04 08:16
Isn't this issue a duplicate of #1?

**Comment by leonchen83** [comment] 2017-05-04 10:47
yep ,but I saw [#1](https://github.com/RedisLabsModules/rejson/issues/1) has closed. so I opened this issue

**Comment by itamarhaber** [comment] 2017-05-04 11:00
Sorry, I meant, isn't that #3?

**Comment by leonchen83** [comment] 2017-05-04 11:06
yes ,pls close this issue

**Comment by itamarhaber** [comment] 2017-05-04 11:54
Cool

**Closed by itamarhaber** 2017-05-04 11:54 UTC
Labels: duplicate
